"""users table

Revision ID: 0c6ccca5be24
Revises: 25bfb7e33f9c
Create Date: 2022-03-07 14:15:08.159822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6ccca5be24'
down_revision = '25bfb7e33f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('title', sa.String(length=64), nullable=False))
    op.add_column('user', sa.Column('scheduled_time', sa.String(), nullable=False))
    op.add_column('user', sa.Column('should_alert', sa.Boolean(), nullable=False))
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')
    op.drop_column('user', 'email')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_column('user', 'should_alert')
    op.drop_column('user', 'scheduled_time')
    op.drop_column('user', 'title')
    # ### end Alembic commands ###
