"""users table

Revision ID: c39c299237ba
Revises: 0c6ccca5be24
Create Date: 2022-03-08 15:43:28.273077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39c299237ba'
down_revision = '0c6ccca5be24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('done', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('update_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'update_at')
    op.drop_column('user', 'create_at')
    op.drop_column('user', 'done')
    # ### end Alembic commands ###
